# Generated by Django 4.2.7 on 2023-11-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_user_joined_date_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='minerva_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='joined_date',
        ),
        migrations.AddField(
            model_name='user',
            name='residence_hall',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
