# Generated by Django 4.2.7 on 2023-11-03 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_email_user_minerva_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
