# Generated by Django 4.2.7 on 2023-11-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_post_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='minerva_email',
            field=models.EmailField(default='jayjay@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
