# Generated by Django 4.2.7 on 2023-11-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_post_minerva_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='by_this_time',
            new_name='by_this_date_and_time',
        ),
    ]
